In [1]:
import numpy as np


In [2]:
a= np.array([1,2, 8.9])

In [3]:
a

array([1. , 2. , 8.9])

In [4]:
a.shape

(3,)

In [9]:
b=np.array([1,2,8.9, "string"])
b

array(['1', '2', '8.9', 'string'], dtype='<U32')

In [11]:
c=np.array([1,2,3,4],dtype="float")
c

array([1., 2., 3., 4.])

In [5]:
len(dir(np))

603

In [13]:
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
d.shape

(2, 3)

In [15]:
d[0][1]

2

In [16]:
e=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[9,10,11]]])
e

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  6,  7],
        [ 9, 10, 11]]])

In [17]:
e.shape

(2, 2, 3)

In [48]:
f=np.array([[[[1,2,4]],[[8,9,7]]],[[[9,8,6]],[[9,6,5]]],[[[1,2,4]],[[8,9,7]]],[[[9,8,6]],[[9,6,5]]]])
f

array([[[[1, 2, 4]],

        [[8, 9, 7]]],


       [[[9, 8, 6]],

        [[9, 6, 5]]],


       [[[1, 2, 4]],

        [[8, 9, 7]]],


       [[[9, 8, 6]],

        [[9, 6, 5]]]])

In [49]:
f.shape

(4, 2, 1, 3)

### Numpy.arange

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [38]:
arr1=np.arange(0,12).reshape(4,-1)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
arr1.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [39]:
arr1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
np.zeros((4,3), dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
np.ones((4,3), dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
np.diag([1,2,3,7])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

In [54]:
np.identity(4, dtype="float")

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
np.eye(4, dtype="float")

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [80]:
np.identity(3,4)

TypeError: Cannot interpret '4' as a data type

In [91]:
arr2=np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
np.triu(arr2)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [93]:
np.tril(arr2)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [94]:
np.triu(arr2,k=-1)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 8, 9]])

In [95]:
np.triu(arr2,k=0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [98]:
np.triu(arr2,k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [55]:
import random

In [56]:
np.random.rand(10)

array([0.68130665, 0.48507448, 0.73135682, 0.38613304, 0.83346063,
       0.12016734, 0.10535881, 0.53711035, 0.85593049, 0.63891709])

In [59]:
np.random.randint(1,10, size=(3,3))

array([[7, 3, 8],
       [3, 6, 8],
       [5, 4, 3]])

In [72]:
list1=["apple","banana","cherry","strawberry","orange","mango","papaya","jackfruit"]

In [74]:
random.sample(list1,2)

['jackfruit', 'banana']

### Broadcasting

In [60]:
A=np.arange(12).reshape(4,3)

In [61]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
B=np.arange(3).reshape(1,3)
B

array([[0, 1, 2]])

In [66]:
A+B

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

### Transpose

In [76]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [77]:
arr1.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

### vstack & hstack

In [99]:
a=np.array([[1,2],[3,4]])
b=np.array([[7,9],[9,10]])

In [101]:
np.hstack((a,b))

array([[ 1,  2,  7,  9],
       [ 3,  4,  9, 10]])

In [102]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 7,  9],
       [ 9, 10]])

### asarray

In [122]:
arr5=(7,8,9)

arr5=np.asarray(arr5)
arr5

array([7, 8, 9])

In [108]:
type(arr5)

numpy.ndarray

### asanyarray

In [111]:
arr5=(7,8,9)
arr5=np.asanyarray(arr5)
arr5

array([7, 8, 9])

In [110]:
type(arr5)

numpy.ndarray

In [112]:
x=np.array([1,2,3])

In [113]:
y=x ## shallow copy (Referenced y)

In [114]:
z=np.copy(x) ## deep copy 

In [116]:
y[0]=100

In [119]:
x,y,z

(array([100,   2,   3]), array([100,   2,   3]), array([1, 2, 3]))

In [120]:
z[0]=500

In [121]:
x,z

(array([100,   2,   3]), array([500,   2,   3]))

### A new 1-D array initialized from text data in a string

In [135]:
a=np.fromstring('234 234', sep= ' ')
a

array([234., 234.])

In [136]:
np.fromstring('1,2', dtype=int,sep=',')

array([1, 2])

In [137]:
np.fromstring('123_567_89', dtype=int, sep='_')

array([123, 567,  89])

In [138]:
print((np.linspace(1,5,50)))

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [139]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [140]:
np.linspace(1,5,20, endpoint=True)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [143]:
np.linspace(2.0,3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [146]:
np.logspace(2.0,3.0, num=4,base=10) ## 10^2=100, 10^3=1000

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [147]:
np.logspace(2.0,3.0, num=4,base=2)

array([4.        , 5.0396842 , 6.34960421, 8.        ])